---
- name: Variabls Demo
  hosts: g1
  become: yes
  vars:
    myusername: Sam

  tasks:
  - name: Update update page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html
      force: yes
...      